### ISSUE TITLE
I can't open the omages after downloaded. Please let me know how to fix this issue

### ISSUE THREAD

**Issue by aalzooke** [jinnovation/rainy-image-dataset#1]

**Comment by jinnovation** [comment]
What error are you receiving? Hard for me to help with next to no context.

**Comment by mozi22** [comment]
Hi, I am having the same problem. I cloned the repository. Opened the image but the image is not opening on a simple Image viewer software. Only shows `blank (black) image`. 

I directly `downloaded the ground truth 1.jpg` and compared the size with the `cloned 1.jpg`. The sizes are different. The cloned one is 131 bytes while the original image size is 326.8 kb. 

Can you please help out.
