### ISSUE TITLE
Can't open cloned images

### ISSUE THREAD

**Issue by mozi22** [jinnovation/rainy-image-dataset#3]
Hi,  I cloned the repository. Opened the image but the image is not opening on a simple Image viewer software. Only shows blank (black) image.

I directly downloaded the ground truth 1.jpg and compared the size with the cloned 1.jpg. The sizes are different. The cloned one is 131 bytes while the original image size is 326.8 kb.

Can anyone please help out

**Comment by jinnovation** [comment]
Try installing [Git LFS](https://git-lfs.github.com/) and re-downloading the files.

Apologies for the confusion; this repository's use of Git LFS is unfortunately undocumented (see #2).
